source $HOME/.vim/config/plug.vim
source $HOME/.vim/config/vim-better-whitespace.vim
source $HOME/.vim/config/ctrlp.vim
source $HOME/.vim/config/airlines.vim
source $HOME/.vim/config/gruvbox.vim
source $HOME/.vim/config/theme.vim
source $HOME/.vim/config/syntastic.vim
source $HOME/.vim/config/vim.vim
source $HOME/.vim/config/mappings.vim
source $HOME/.vim/config/phpcs.vim
source $HOME/.vim/config/autocomplete.vim
source $HOME/.vim/config/debugger.vim
source $HOME/.vim/config/highlighters.vim
